version: "3.9"
services:
  db:
    image: postgres
    ports:
      - target: 5432
        published: 5432
    volumes:
      - type: volume
        source: data
        target: /var/lib/postgresql/data
      - type: bind
        source: ./init_db.sql
        target: /docker-entrypoint-initdb.d/init_db.sql
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - target: 8080
        published: 8080

volumes:
  data: {}
